# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0-noble AS build
WORKDIR /src
COPY ["backend.csproj", "./"]
RUN dotnet restore "backend.csproj"
COPY . .
RUN dotnet publish "backend.csproj" -c Release -o /app/publish

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0-noble AS runtime
WORKDIR /app
COPY --from=build /app/publish .


ENV ASPNETCORE_URLS=http://0.0.0.0:5150

EXPOSE 5150

ENTRYPOINT ["dotnet", "backend.dll"]
